import './globals.css'

export const metadata = {
  title: 'Spotify using Tailwind',
  description: 'Generated by create next app and styled using tailwind',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-zinc-900 text-zinc-50'>{children}</body>
    </html>
  )
}
